name: Feature Branch Validation
on:
    push:
        branches:
            - 'feature/**'
    pull_request:
        branches:
            - 'feature/**' 
permissions:
    contents: write
    
jobs:
    validation:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup NodeJs
              uses: actions/setup-node@v4
              with:
                node-version: 22
            
            - name: Install Dependencies
              working-directory: src
              run: npm ci

            - name: Prettier Check
              working-directory: src
              run: npm run format:check

            - name: ESLint
              working-directory: src
              run: npm run lint

            - name: Dependency Audit
              working-directory: src
              run: npm audit --audit-level=high
            
            - name: Unit Tests
              working-directory: src
              run: npm test

            - name: Build Validation
              working-directory: src
              run: npm run build
