name: Secret's Scan

on:
    push:
    pull_request:
jobs:
    gitleaks:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: read

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: gitleaks/gitleaks-action@v3
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}