name: Semgrep SAST
on:
    push:
        branches:
            - develop
            - main
            - "feature/**"
    pull_request:
        branches:
            - develop
            - main

permissions:
    contents: read
    security-events: write

jobs:
    semgrep:
        name: Static Application Security Testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 8

            - name: Run Semgrep
              uses: semgrep/semgrep-action@v1
              with:
                config: p/security-audit

        

        



